# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tarla.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: João Tarla Blog
  avatar: # avatar.png
  gravatar: # Email MD5 hash
  description: "A blog about code and stuff and code" # used by search engines

  # Header and footer text
  header_text: >
     <h2>A blog about code and stuff.</h2>
     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  header_text_feature_image: "img/sample_feature_img.png"
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> with ♥

  # Icons
  rss: false
  email_address: # "joao@tarla.com.br"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "tarla"
  google_plus:
  instagram:
  linkedin:  "https://linkedin.com/in/joaotarla"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "joaotarla"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
